<?php

// include_paths.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    $vendorDir . '/aristath/kirki',
    $vendorDir . '/aristath/kirki/core',
);
