<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => NULL,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => NULL,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'altorouter/altorouter' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'f6fede4f94ced7c22ba63a9b8af0bf2dc38e3cb2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../altorouter/altorouter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'aristath/kirki' => array(
            'pretty_version' => '4.0.24',
            'version' => '4.0.24.0',
            'reference' => '810938ec2b095966774784a27880f4aeba2d2853',
            'type' => 'library',
            'install_path' => __DIR__ . '/../aristath/kirki',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/installers' => array(
            'pretty_version' => 'v2.1.1',
            'version' => '2.1.1.0',
            'reference' => 'af93ba6e52236418f07a278033eba6959ee5b983',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'htmlburger/carbon-fields' => array(
            'pretty_version' => 'v3.3.4',
            'version' => '3.3.4.0',
            'reference' => '2ae6773c004b873a1b0456613b14852c1a436a96',
            'type' => 'library',
            'install_path' => __DIR__ . '/../htmlburger/carbon-fields',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/compatibility' => array(
            'pretty_version' => 'v1.0.12',
            'version' => '1.0.12.0',
            'reference' => '9229a0bfff5740be5a1f437d69add1794e5fbd81',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/compatibility',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-base' => array(
            'pretty_version' => 'v1.0.4',
            'version' => '1.0.4.0',
            'reference' => '0abf9e81f21e5256be879240cca98778e99851eb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-base',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-checkbox' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'reference' => '1f581fd75cf9cae20788decbe56d5ef48d3b7bf8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-checkbox',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-code' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => '88e7b01127fc7039e2c1fc6761184b0332f9a0c3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-color' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '5820fa89e0e8dc69dd4864575074552434193e11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-color',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-color-palette' => array(
            'pretty_version' => 'v1.0.3',
            'version' => '1.0.3.0',
            'reference' => '32715837449e9a6666253b28b538bd69d6718c67',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-color-palette',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-cropped-image' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '549e7ddfe1a9fe2305fe6c1bc6cc80489d647452',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-cropped-image',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-custom' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '103f4f813f1919c23ec41e81c81cfbf83ab0e78f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-custom',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-dashicons' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '90210466bd4a53b6ab4468330064eabeaf242fd9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-dashicons',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-date' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '71e7fb60b5789d77579b12b202e5487cd2bd5dc2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-date',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-dimension' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => '7a64c587fd57fb5bdbeceb393b621457c4d9f515',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-dimension',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-editor' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '5e27c3cc7b10eb317321790a5d8ddf57304cf2a2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-editor',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-generic' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => '5f87bb740ba92717b6b10b862e571919003906c4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-generic',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-image' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => '32e2a2aff8a7e5d6ff9dfe530563a4381dc82e61',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-image',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-multicheck' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => '90098008c1988e7cd2b84c75ece68bbcd3bbeb70',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-multicheck',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-palette' => array(
            'pretty_version' => 'v0.1.1',
            'version' => '0.1.1.0',
            'reference' => 'aca16701c2aaddab0cef3e429cdb753845e03ae0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-palette',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-radio' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => '1e47f185f8d95005c83e0ffbf3ff09faecea8eac',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-radio',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-react-colorful' => array(
            'pretty_version' => 'v1.0.17',
            'version' => '1.0.17.0',
            'reference' => '79258cdbcdd4ee8582560edc4a09c8ba45eaf219',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-react-colorful',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-react-select' => array(
            'pretty_version' => 'v1.1.5',
            'version' => '1.1.5.0',
            'reference' => '4c156e42a36f74ff5b9b1e2797b1742845de9e47',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-react-select',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-repeater' => array(
            'pretty_version' => '1.0.5',
            'version' => '1.0.5.0',
            'reference' => '5375e65054b7a73da4e735fa7bee831c7f6c1cfc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-repeater',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-select' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '01abe2cbce62b7a566c890697a32506b94910156',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-select',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-slider' => array(
            'pretty_version' => 'v1.0.5',
            'version' => '1.0.5.0',
            'reference' => '40ce473123f0cb12da745467d69210cff3ffecf5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-slider',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-sortable' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'ea4659bb2118c57ec6e24cd2ab06f36a3a528d26',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-sortable',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/control-upload' => array(
            'pretty_version' => 'v1.0.3',
            'version' => '1.0.3.0',
            'reference' => '13ea09c9330c6eb1d4452d5948866f226b0f8a0f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-upload',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/data-option' => array(
            'pretty_version' => 'v1.0.3',
            'version' => '1.0.3.0',
            'reference' => '9a54f5c553e2f1e84f4ff620e271bfc16ee49ced',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/data-option',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/field' => array(
            'pretty_version' => 'v1.0.10',
            'version' => '1.0.10.0',
            'reference' => '97f5bf659cc68d46e2bce62489acf2d2142b36e7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/field-background' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '875b5e42c3de8a77d0a15c7dd55c8467cbf18373',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field-background',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/field-dimensions' => array(
            'pretty_version' => 'v1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'ac147cc95fb706664953471ef8f14cfb04f197fc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field-dimensions',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/field-fontawesome' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '64d8954039eef1ff03429cdd13c81e4e6b278321',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field-fontawesome',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/field-multicolor' => array(
            'pretty_version' => 'v1.0.3',
            'version' => '1.0.3.0',
            'reference' => '3e0df3f5548fb89b38cb144bc87992936ed7b536',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field-multicolor',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/field-typography' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'reference' => '2d96fc2d65325ce8474d55e083db742cf437c0dd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field-typography',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/googlefonts' => array(
            'pretty_version' => '1.0.4',
            'version' => '1.0.4.0',
            'reference' => '3fa0b6b5aacda3213ca7ccedcba3e6906aecb409',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/googlefonts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/l10n' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => '5a40875434ca075a09c81952547e3ccc7eeef704',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/l10n',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/module-css' => array(
            'pretty_version' => 'v1.0.11',
            'version' => '1.0.11.0',
            'reference' => 'b53cff693b489cc7e4991ef725a66ddafa8aa84b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-css',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/module-editor-styles' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'a86f8b66fa0a442ce092c122b997c8d5f8d20951',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-editor-styles',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/module-field-dependencies' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'reference' => '5bf94bdce480d8405136cd5f0013ef42a775f167',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-field-dependencies',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/module-panels' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '1599dd344c15c49a837b5fdbddb1e37544bef979',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-panels',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/module-postmessage' => array(
            'pretty_version' => '1.0.7',
            'version' => '1.0.7.0',
            'reference' => '9b2b419027f3b95a2546041a83fc5607492f35a5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-postmessage',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/module-preset' => array(
            'pretty_version' => 'v1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'b4862fbeb9e441ed4ccd15f29a1d17d6f300f6a9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-preset',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/module-section-icons' => array(
            'pretty_version' => 'v0.1.0',
            'version' => '0.1.0.0',
            'reference' => '0e77b904692772974e5e291143f45056a5ab3665',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-section-icons',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/module-sections' => array(
            'pretty_version' => 'v1.0.4',
            'version' => '1.0.4.0',
            'reference' => 'ee8c9120ddd7fe63e1ca39db93714b9b4e5d477c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-sections',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/module-selective-refresh' => array(
            'pretty_version' => 'v1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'bfeb430cb7eff60f5ba79e0785cf413905202c42',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-selective-refresh',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/module-tooltips' => array(
            'pretty_version' => 'v1.0.10',
            'version' => '1.0.10.0',
            'reference' => '5b4715bd236a4239356e408068bffc2f300f3cdf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-tooltips',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/module-webfonts' => array(
            'pretty_version' => 'v1.0.5',
            'version' => '1.0.5.0',
            'reference' => '6be8c298abc29bccc227e1b1dbcb029e6a072659',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-webfonts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/url-getter' => array(
            'pretty_version' => 'v1.0.5',
            'version' => '1.0.5.0',
            'reference' => 'cfe7ea5b51c5e9b5e7d706ed56694f54a972fae2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/url-getter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kirki-framework/util' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'fa3deaafe48055b56aedf80501817e3d9e83211c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/util',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => '6fd1b9a79f6e3cf65f9e679b23af304cd9e010d4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => '9344f9cb97f3b19424af1a21a3b0e75b0a7d8d7e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => 'bf44a9fd41feaac72b074de600314a93e2ae78e2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'timber/timber' => array(
            'pretty_version' => '1.20.0',
            'version' => '1.20.0.0',
            'reference' => '3ac8c7629656009b9e0d6d9e4ccda202aad3b8e0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../timber/timber',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'twig/cache-extension' => array(
            'pretty_version' => 'v1.5.0',
            'version' => '1.5.0.0',
            'reference' => '2c243643f59132194458bd03c745b079bbb12e78',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/cache-extension',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'twig/twig' => array(
            'pretty_version' => 'v2.15.2',
            'version' => '2.15.2.0',
            'reference' => '3e43405a9a8b578809426339cc3780e16fba0c52',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'upstatement/routes' => array(
            'pretty_version' => '0.9.1',
            'version' => '0.9.1.0',
            'reference' => 'cac3c844ab824e4039fd26edbea5402415aa6d0a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../upstatement/routes',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wpcl/wpconsole' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '130d4b375261dd6b7fc0511dadafa870e7ef7370',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wpcl/wpconsole',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
